// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'hero_checkbox.dart';

// **************************************************************************
// MixWidgetGenerator
// **************************************************************************

/// Styler recipe for `HeroCheckbox`.
///
/// The widget class is generated by `@MixWidget`; its name is derived from this
/// function (`heroCheckboxStyle` → `HeroCheckbox`). The `variant` parameter also
/// produces the `HeroCheckbox.primary()` / `HeroCheckbox.secondary()` named
/// constructors.
class HeroCheckbox extends StatelessWidget {
  const HeroCheckbox({
    super.key,
    this.size = .md,
    this.variant = .primary,
    this.error = false,
    this.style,
    required this.selected,
    this.onChanged,
    this.enabled = true,
    this.tristate = false,
    this.checkedIcon = Icons.check_rounded,
    this.uncheckedIcon,
    this.indeterminateIcon = Icons.horizontal_rule,
    this.focusNode,
    this.autofocus = false,
    this.enableFeedback = true,
    this.semanticLabel,
    this.mouseCursor = SystemMouseCursors.click,
  });

  const HeroCheckbox.primary({
    super.key,
    this.size = .md,
    this.error = false,
    this.style,
    required this.selected,
    this.onChanged,
    this.enabled = true,
    this.tristate = false,
    this.checkedIcon = Icons.check_rounded,
    this.uncheckedIcon,
    this.indeterminateIcon = Icons.horizontal_rule,
    this.focusNode,
    this.autofocus = false,
    this.enableFeedback = true,
    this.semanticLabel,
    this.mouseCursor = SystemMouseCursors.click,
  }) : variant = HeroCheckboxVariant.primary;

  const HeroCheckbox.secondary({
    super.key,
    this.size = .md,
    this.error = false,
    this.style,
    required this.selected,
    this.onChanged,
    this.enabled = true,
    this.tristate = false,
    this.checkedIcon = Icons.check_rounded,
    this.uncheckedIcon,
    this.indeterminateIcon = Icons.horizontal_rule,
    this.focusNode,
    this.autofocus = false,
    this.enableFeedback = true,
    this.semanticLabel,
    this.mouseCursor = SystemMouseCursors.click,
  }) : variant = HeroCheckboxVariant.secondary;

  final HeroCheckboxSize size;

  final HeroCheckboxVariant variant;

  final bool error;

  final RemixCheckboxStyler? style;

  final bool? selected;

  final ValueChanged<bool?>? onChanged;

  final bool enabled;

  final bool tristate;

  final IconData checkedIcon;

  final IconData? uncheckedIcon;

  final IconData indeterminateIcon;

  final FocusNode? focusNode;

  final bool autofocus;

  final bool enableFeedback;

  final String? semanticLabel;

  final MouseCursor mouseCursor;

  @override
  Widget build(BuildContext context) {
    return heroCheckboxStyle(
      size: this.size,
      variant: this.variant,
      error: this.error,
      style: this.style,
    ).call(
      key: this.key,
      selected: this.selected,
      onChanged: this.onChanged,
      enabled: this.enabled,
      tristate: this.tristate,
      checkedIcon: this.checkedIcon,
      uncheckedIcon: this.uncheckedIcon,
      indeterminateIcon: this.indeterminateIcon,
      focusNode: this.focusNode,
      autofocus: this.autofocus,
      enableFeedback: this.enableFeedback,
      semanticLabel: this.semanticLabel,
      mouseCursor: this.mouseCursor,
    );
  }
}
