// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'hero_switch.dart';

// **************************************************************************
// MixWidgetGenerator
// **************************************************************************

/// Styler recipe for `HeroSwitch`.
///
/// The widget class is generated by `@MixWidget`; its name is derived from this
/// function (`heroSwitchStyle` → `HeroSwitch`).
class HeroSwitch extends StatelessWidget {
  const HeroSwitch({
    super.key,
    this.size = .md,
    this.style,
    required this.selected,
    this.onChanged,
    this.enabled = true,
    this.enableFeedback = true,
    this.focusNode,
    this.autofocus = false,
    this.semanticLabel,
    this.mouseCursor = SystemMouseCursors.click,
  });

  final HeroSwitchSize size;

  final RemixSwitchStyler? style;

  final bool selected;

  final ValueChanged<bool>? onChanged;

  final bool enabled;

  final bool enableFeedback;

  final FocusNode? focusNode;

  final bool autofocus;

  final String? semanticLabel;

  final MouseCursor mouseCursor;

  @override
  Widget build(BuildContext context) {
    return heroSwitchStyle(size: this.size, style: this.style).call(
      key: this.key,
      selected: this.selected,
      onChanged: this.onChanged,
      enabled: this.enabled,
      enableFeedback: this.enableFeedback,
      focusNode: this.focusNode,
      autofocus: this.autofocus,
      semanticLabel: this.semanticLabel,
      mouseCursor: this.mouseCursor,
    );
  }
}
