import 'package:flutter/material.dart';
import 'package:mix_annotations/mix_annotations.dart';
import 'package:remix/remix.dart';

import '../../tokens/hero_tokens.dart';

part 'hero_switch.g.dart';

enum HeroSwitchSize with EnumVariant { sm, md, lg }

/// Styler recipe for `HeroSwitch`.
///
/// The widget class is generated by `@MixWidget`; its name is derived from this
/// function (`heroSwitchStyle` → `HeroSwitch`).
@MixWidget()
RemixSwitchStyler heroSwitchStyle({
  HeroSwitchSize size = .md,
  RemixSwitchStyler? style,
}) {
  return _baseStyle().merge(_sizeStyle()).merge(style).applyVariants([size]);
}

/// Unselected thumb shadow (CSS: shadow-field).
final _thumbShadow = BoxShadowMix()
    .color(const Color(0x0A000000))
    .offset(x: 0, y: 2)
    .blurRadius(4);

/// Selected thumb shadow (CSS: stronger shadow on checked state).
final _thumbShadowSelected = BoxShadowMix()
    .color(const Color(0x0F000000))
    .offset(x: 0, y: 2)
    .blurRadius(10);

RemixSwitchStyler _baseStyle() {
  return RemixSwitchStyler()
      .container(
        BoxStyler().alignment(.centerLeft).paddingAll(2).borderRounded(999),
      )
      .color($default())
      .thumbColor(Colors.white)
      .thumb(BoxStyler().borderRounded(999).shadow(_thumbShadow))
      .onSelected(
        RemixSwitchStyler()
            .color($accent())
            .thumbColor($accentForeground())
            .thumb(BoxStyler().shadow(_thumbShadowSelected))
            .onHovered(RemixSwitchStyler().color($accentHover()))
            .onPressed(RemixSwitchStyler().color($accentHover())),
      )
      .onDisabled(
        RemixSwitchStyler()
            .color($default())
            .thumbColor(const Color(0x33000000))
            .wrap(.opacity(0.5))
            .onSelected(
              RemixSwitchStyler().thumbColor(const Color(0x66FFFFFF)),
            ),
      )
      .animate(.easeOut(200.ms));
}

RemixSwitchStyler _sizeStyle() {
  return RemixSwitchStyler()
      .variant(
        HeroSwitchSize.sm,
        RemixSwitchStyler().size(32, 16).thumb(.size(16.5, 12)),
      )
      .variant(
        HeroSwitchSize.md,
        RemixSwitchStyler().size(40, 20).thumb(.size(22, 16)),
      )
      .variant(
        HeroSwitchSize.lg,
        RemixSwitchStyler().size(48, 24).thumb(.size(27.5, 20)),
      );
}
