// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'hero_radio.dart';

// **************************************************************************
// MixWidgetGenerator
// **************************************************************************

/// Styler recipe for `HeroRadio`.
///
/// The widget class is generated by `@MixWidget`; its name is derived from this
/// function (`heroRadioStyle` → `HeroRadio`). The generated widget is generic
/// (`HeroRadio<T>`), inheriting `<T>` from `RemixRadioStyler.call<T>`; `variant`
/// also produces the `.primary()` / `.secondary()` named constructors.
class HeroRadio<T> extends StatelessWidget {
  const HeroRadio({
    super.key,
    this.size = .md,
    this.variant = .primary,
    this.error = false,
    this.style,
    required this.value,
    this.enabled = true,
  });

  const HeroRadio.primary({
    super.key,
    this.size = .md,
    this.error = false,
    this.style,
    required this.value,
    this.enabled = true,
  }) : variant = HeroRadioVariant.primary;

  const HeroRadio.secondary({
    super.key,
    this.size = .md,
    this.error = false,
    this.style,
    required this.value,
    this.enabled = true,
  }) : variant = HeroRadioVariant.secondary;

  final HeroRadioSize size;

  final HeroRadioVariant variant;

  final bool error;

  final RemixRadioStyler? style;

  final T value;

  final bool enabled;

  @override
  Widget build(BuildContext context) {
    return heroRadioStyle(
      size: this.size,
      variant: this.variant,
      error: this.error,
      style: this.style,
    ).call<T>(key: this.key, value: this.value, enabled: this.enabled);
  }
}
